[package]
name = "runen"
version = "0.0.1"
edition = "2021"
authors = ["Sergey Reshetnikov <shaman@simmirra.com>"]

[dependencies]
regex = "1.11.0"

[lib]
name = "librunen"
path = "src/lib.rs"

[[bin]]
name = "num_converter"
path = "src/num_converter.rs"
