[package]
name = "runen"
version = "0.1.3"
edition = "2021"
authors = ["Sergey Reshetnikov <shaman@simmirra.com>"]
license = "MIT"

[dependencies]
cargo-xtask = "0.1.0"
regex = "1.11.1"
tokio = { version = "1.41.1", features = ["full"] }
tokio-stream = { version = "0.1.16", features = ["full"] }
tokio-util = { version = "0.7.12", features = ["full"] }

[lib]
name = "librunen"
path = "src/lib.rs"
