[package]
name = "runen"
version = "0.0.8"
edition = "2021"
authors = ["Sergey Reshetnikov <shaman@simmirra.com>"]

[dependencies]
as_any = { path = "./macros/as_any" }
as_any_derive = { path = "./macros/as_any/as_any_derive" }
cargo-xtask = "0.1.0"
regex = "1.11.1"

[lib]
name = "librunen"
path = "src/lib.rs"

[[bin]]
name = "num_converter"
path = "src/num_converter.rs"
